version: '3.8'

services:
  backend:
    build: ./backend
    container_name: esp32-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MQTT_BROKER=8.135.238.216
      - MQTT_PORT=1883
      - MQTT_USER=admin
      - MQTT_PASS=admin
      - MONGODB_URI=mongodb://mongo_miXkxe:mongo_NQf5WW@8.135.238.216:27017/esp32_epd?authSource=admin
      - MONGODB_DB=esp32_epd
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: esp32-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
